### ISSUE TITLE
Local resources

### ISSUE THREAD

**Issue by Default4152** [kkrishnak/prj-rev-bwfs-dasmoto#2]
Simplify - I recommend downloading the images and sticking them into a local resource folder. This will allow for faster page loading and less reliance on external servers. On top of this, if the remote site decides to change the URL of the image without your knowledge, you'll have to find what the new URL is and update your HTML accordingly which creates maintenance load.

**Comment by kkrishnak** [comment]
Thank you for your preview. At the starting of my project,I actually downloaded and created images in the resources folder and tried your suggestion. It went nice. After seeing the stuff going, i had done the normal procedure by creating the images through remote URL's.
