### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Default4152** [kkrishnak/prj-rev-bwfs-dasmoto#4]
Grade: **Meets Expectations**

This project is working great! I really like your usage of descriptive class names, and how consistent your HTML was in indentation and spacing. A couple things I would change is making sure you add alt attributes to your images and downloading those images to put into a local resource folder. Next steps, I would look into learning about media queries in an effort to make your pages responsive so they will be viewable on all types of media such as phone, PC, laptop, etc: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries 

Nicely done!

**Comment by kkrishnak** [comment]
Thanks for your Preview and Suggestions.
